import os


__all__ = [
    "LEFT_EYE_LEFT_EDGE",
    "LEFT_EYE_TOP_EDGE",
    "LEFT_EYE_RIGHT_EDGE",
    "LEFT_EYE_BOTTOM_EDGE",
    "RIGHT_EYE_LEFT_EDGE",
    "RIGHT_EYE_TOP_EDGE",
    "RIGHT_EYE_RIGHT_EDGE",
    "RIGHT_EYE_BOTTOM_EDGE",
    "NOSE_LEFT_EDGE",
    "NOSE_TOP_EDGE",
    "NOSE_RIGHT_EDGE",
    "NOSE_BOTTOM_EDGE",
    "LIPS_LEFT_EDGE",
    "LIPS_TOP_EDGE",
    "LIPS_RIGHT_EDGE",
    "LIPS_BOTTOM_EDGE",
    # "FACE_OVAL_LEFT_EDGE",
    # "FACE_OVAL_TOP_EDGE",
    # "FACE_OVAL_RIGHT_EDGE",
    # "FACE_OVAL_BOTTOM_EDGE",
]

# Currently defined landmarks
DEFINED_LANDMARKS = [
    "left-eye",
    "right-eye",
    "nose",
    "lips",
]

# Indexes
LEFT_EYE_LEFT_EDGE = 359
LEFT_EYE_TOP_EDGE = 257
LEFT_EYE_RIGHT_EDGE = 362
LEFT_EYE_BOTTOM_EDGE = 449

RIGHT_EYE_LEFT_EDGE = 133
RIGHT_EYE_TOP_EDGE = 27
RIGHT_EYE_RIGHT_EDGE = 226
RIGHT_EYE_BOTTOM_EDGE = 229

NOSE_LEFT_EDGE = 64
NOSE_TOP_EDGE = 27
NOSE_RIGHT_EDGE = 294
NOSE_BOTTOM_EDGE = 2

LIPS_LEFT_EDGE = 61
LIPS_TOP_EDGE = 267
LIPS_RIGHT_EDGE = 291
LIPS_BOTTOM_EDGE = 17

# TODO: Set 'face oval'(얼굴윤곽) indexes
# FACE_OVAL_LEFT_EDGE =
# FACE_OVAL_TOP_EDGE =
# FACE_OVAL_RIGHT_EDGE =
# FACE_OVAL_BOTTOM_EDGE =

# AWS keys to use S3
AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECERT_ACCESS_KEY")

assert AWS_ACCESS_KEY_ID is not None, "`AWS_ACCESS_KEY_ID` Environment Variable is `None`."
assert AWS_SECRET_ACCESS_KEY is not None, "`AWS_SECRET_ACCESS_KEY` Environment Variable is `None`."
